spring:
  datasource:
    password: oG_labolG

  mail:
    host: smtp.gmail.com
    port: 587
    username: dbwnstjs4862@gmail.com
    password: zitdodzrknrltkxc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# OAuth2 Client Secret
#구글
OAUTH2_GOOGLE_SECRET: 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
#카카오
OAUTH2_KAKAO_CLIENT_ID: 1b7799a25e73e36ef669def0f4415b25
#네이버
OAUTH2_NAVER_CLIENT_ID: DfPHMRzqnIpZ6o5XVycS
OAUTH2_NAVER_CLIENT_SECRET: kgx6IyVBqk



jwt:
  secret: UqZ7E8G3DpA5OaWTdpFh4wYJmCtVzj9qTnVrpKmci8Ocf+8whKZQLqD1dZpgMq3W

openai:
  api-key: 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